import { Test, TestingModule } from '@nestjs/testing';
import { TokenService } from './token.service';

describe('TokenService', () => {
    let service: TokenService;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            providers: [TokenService],
        }).compile();

        service = module.get<TokenService>(TokenService);
    });

    it('should be defined', () => {
        expect(service).toBeDefined();
    });

    describe('generateToken', () => {
        it('should generate tocken and expiration date', () => {
            const [token, expirationTime] = service.generateToken();

            expect(expirationTime).toBeDefined();
            expect(token).toBeDefined();
        });
    });

    describe('decodeToken', () => {
        it('should decode data that is generated by generateToken', () => {
            const [token, expirationTime] = service.generateToken();
            expect(service.decodeToken(token).getTime()).toBe(expirationTime.getTime());
        });

        it('should throw error if token is invalid', () => {
            const invalidToken = '7f593b18d365d9ab763eb5530e078bd5MTczMzc3MjI3MDE2NA==';
            expect(() => {
                service.decodeToken(invalidToken);
            }).toThrow();
        });
    });
});
